name: Main

on:
  issue_comment:
    types:
      - created
  pull_request:
    branches: [main, release]
  push:
    branches: [main, release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 12
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12'
      - name: Install Dependencies
        run: |-
          yarn install --frozen-lockfile
