name: Main

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - run: sleep 300

